{% set name = "hpp-manipulation" %}
{% set version = "9.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2401ff6e3ed6aa82e94dc08cb8710848696c8ba1925f2570822e411dd06cab92

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
    - doxygen
  host:
    - libboost-devel
    - tinyxml2
    - urdfdom
    - assimp
    - octomap
    - hpp-fcl
    - qhull
    - qhull-static
    - hpp-util  {{ version }}
    - hpp-statistics  {{ version }}
    - hpp-pinocchio  {{ version }}
    - hpp-constraints  {{ version }}
    - hpp-core  {{ version }}
    - proxsuite
  run:
    - tinyxml2
    - qhull
    - qhull-static
    - proxsuite

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/humanoid-path-planner/{{ name }}
  license: BSD-2-Clause
  license_file: LICENSE
  summary: {{ name }} subpackage of Humanoid Path Planner suite
  description: |
    HPP (Humanoid Path Planner) is a collection of software packages implementing
    path planning functionalities for a humanoid robot. The core functionalities are well
    suited to solve classical path planning problems. It can be extended to path planning
    for other types of robots like digital actors for instance.
  doc_url: https://gepettoweb.laas.fr/hpp/hpp-doc/doxygen-html/index.html
  dev_url: https://github.com/humanoid-path-planner/{{ name }}

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
